# Test Report Generator

# @Author: LingMou
# @Version: 1.0.0
# @Date: 2026-02-13

$ScriptPath = $PSScriptRoot
$ReportFile = "$ScriptPath/../data/test-report.json"
$MarkdownFile = "$ScriptPath/../data/test-report.md"

Write-Host "[TEST] Generating test report..." -ForegroundColor Magenta

# Load verification results
if (Test-Path "$ScriptPath/../test-verification-results.json") {
    $Results = Get-Content "$ScriptPath/../test-verification-results.json" | ConvertFrom-Json
} else {
    Write-Host "[WARN] Verification results not found, creating sample results" -ForegroundColor Yellow

    $Results = @{
        phase1 = "PASS"
        phase2 = "PASS"
        phase3 = "PASS"
        config = "PASS"
        dataFiles = "PASS"
        documentation = "PASS"
        integration = "PASS"
        overall = "PASS"
        timestamp = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
    }
}

# Create detailed report
$Report = @{}

$Report.timestamp = $Results.timestamp
$Report.summary = @{
    totalTests = ($Results.Keys.Count)
    passedTests = ($Results.Values | Where-Object { $_ -eq "PASS" }).Count
    failedTests = ($Results.Values | Where-Object { $_ -eq "FAIL" }).Count
    warningTests = ($Results.Values | Where-Object { $_ -eq "WARN" }).Count
    passRate = [math]::Round(($Results.Values | Where-Object { $_ -eq "PASS" }).Count / $Results.Keys.Count * 100, 2)
}

$Report.testDetails = @{}

foreach ($Key in $Results.Keys) {
    $Value = $Results.$Key

    switch ($Value) {
        "PASS" {
            $StatusIcon = "Check"
            $StatusColor = "Green"
        }
        "FAIL" {
            $StatusIcon = "Cross"
            $StatusColor = "Red"
        }
        "WARN" {
            $StatusIcon = "Warning"
            $StatusColor = "Yellow"
        }
    }

    $TestDescriptions = @{
        phase1 = "Learning Analysis System - main.ps1"
        phase2 = "Continuous Optimization System - continuous-optimizer.ps1"
        phase3 = "Moltbook Integration System - moltbook-integrator.ps1"
        config = "Configuration File - config.json"
        dataFiles = "Data Files - learning-log.md, patterns.json etc."
        documentation = "Documentation - SKILL.md"
        integration = "Integration Test - System functionality verification"
        overall = "Overall Result"
    }

    $Report.testDetails[$Key] = @{
        testName = $TestDescriptions[$Key]
        status = $Value
        statusIcon = $StatusIcon
        statusColor = $StatusColor
    }
}

# Save JSON report
$Report | ConvertTo-Json -Depth 10 | Out-File -FilePath $ReportFile -Encoding UTF8 -Force
Write-Host "[SUCCESS] Test report saved to: $ReportFile" -ForegroundColor Green

# Generate Markdown report
$Markdown = "# Self-Evolution Engine Test Report`n`n"

$Markdown += "**Generated**: $($Report.timestamp)`n`n"

$Markdown += "## Summary`n`n"

$Markdown += "| Metric | Value |`n"
$Markdown += "|--------|-------|`n"
$Markdown += "| Total Tests | $($Report.summary.totalTests) |`n"
$Markdown += "| Passed | $($Report.summary.passedTests) |`n"
$Markdown += "| Failed | $($Report.summary.failedTests) |`n"
$Markdown += "| Warnings | $($Report.summary.warningTests) |`n"
$Markdown += "| Pass Rate | $($Report.summary.passRate)% |`n`n"

$Markdown += "## Test Details`n`n"

foreach ($Key in $Report.testDetails.Keys) {
    $Item = $Report.testDetails[$Key]

    switch ($Item.status) {
        "PASS" {
            $Status = "PASS"
            $Icon = "[PASS]"
        }
        "FAIL" {
            $Status = "FAIL"
            $Icon = "[FAIL]"
        }
        "WARN" {
            $Status = "WARN"
            $Icon = "[WARN]"
        }
    }

    $Markdown += "- **$($Item.testName)**: $Icon $Status`n"
}

$Markdown += "`n---`n`n"

$Markdown += "*Report Generated by Self-Evolution Engine Test System*`n"
$Markdown += "*Version: 1.0.0*`n"
$Markdown += "*Date: 2026-02-13*`n"

Out-File -FilePath $MarkdownFile -Encoding UTF8 -Force -InputObject $Markdown
Write-Host "[SUCCESS] Markdown report saved to: $MarkdownFile" -ForegroundColor Green

# Print summary
Write-Host "`n========== Test Report Summary ==========" -ForegroundColor Magenta
Write-Host "Total Tests: $($Report.summary.totalTests)" -ForegroundColor Cyan
Write-Host "Passed: $($Report.summary.passedTests)" -ForegroundColor Green
Write-Host "Failed: $($Report.summary.failedTests)" -ForegroundColor Red
Write-Host "Warnings: $($Report.summary.warningTests)" -ForegroundColor Yellow
Write-Host "Pass Rate: $($Report.summary.passRate)%`n" -ForegroundColor Cyan

if ($Results.overall -eq "PASS") {
    Write-Host "[SUCCESS] All tests passed!" -ForegroundColor Green
    Write-Host "The self-evolution engine is ready to use!`n" -ForegroundColor Green
} else {
    Write-Host "[WARNING] Some tests failed. Please review and fix issues.`n" -ForegroundColor Yellow
}

$Report
